workflows:
  flutter-ios-android:
    name: Flutter iOS & Android Build
    max_build_duration: 60
    environment:
      groups:
        - ios_credentials
      flutter: stable
      xcode: latest
      vars:
        APP_NAME: "EduSathi"

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Set up keychain and certificates
        script: |
          keychain initialize
          keychain add-certificates

      - name: Fetch signing files from App Store Connect
        script: |
          app-store-connect fetch-signing-files \
            "$(xcode-project detect-bundle-id)" \
            --platform IOS \
            --type IOS_APP_STORE \
            --create

      - name: Apply signing to Xcode project
        script: |
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

      - name: Build Android APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/**/*.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "ayushbiharsharif@gmail.com"
