workflows:
  flutter-ios-android:
    name: Flutter iOS & Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - ios_credentials

    scripts:
      - name: Install dependencies
        script: flutter pub get

      # Load your .p12 certificate from environment variable
      - name: Set up certificate
        script: |
          keychain initialize
          keychain add-certificates

      # Download profiles & certificates from App Store Connect API
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "com.techinnovationapp.edusathi" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --platform IOS \
            --type IOS_APP_STORE \
            --create

      - name: Apply signing to Xcode project
        script: xcode-project use-profiles

      - name: Build iOS IPA
        script: flutter build ipa --release

      - name: Build Android APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/**/*.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "ayushbiharsharif@gmail.com"
