workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      groups:
        - ios_credentials

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "com.techinnovationapp.edusathi" \
            --type IOS_APP_STORE \
            --platform IOS \
            --create

      - name: Apply signing
        script: xcode-project use-profiles

      - name: Build IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
